module.exports={
    devServer:{
        host:'localhost',
        port:8080,
        proxy:{
            '/api':{
                target:'http://api-driver.marsview.cc/api/mall/',
                chnageOrigin:true,
                pathRewrite:{
                    '/api':''
                }
            }
        }
    },
    productionSourceMap:true,
    chainWebpack:(config)=>{
        config.plugins.delete('prefetch')
    }
}